# Generated by Django 5.2.2 on 2025-06-09 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_testimonial_category_testimonial_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('schema_markup', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('background_color', models.CharField(blank=True, help_text='e.g. #FFFFFF', max_length=7, null=True)),
                ('text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('section_id', models.CharField(blank=True, help_text='For page anchor navigation', max_length=100, null=True)),
                ('custom_css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('rich_content', ckeditor.fields.RichTextField(verbose_name='Main Content')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Primary Image')),
                ('image_alt_text', models.CharField(blank=True, max_length=255)),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('secondary_image_alt', models.CharField(blank=True, max_length=255)),
                ('gallery_title', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_caption', models.CharField(blank=True, max_length=255)),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('core_values', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('show_feature_list', models.BooleanField(default=False)),
                ('show_counters', models.BooleanField(default=False)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('team_strength', models.PositiveIntegerField(default=0)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.URLField(blank=True)),
                ('cta_icon', models.CharField(blank=True, max_length=100)),
                ('awards_description', ckeditor.fields.RichTextField(blank=True)),
                ('awards_image', models.ImageField(blank=True, null=True, upload_to='about/awards/')),
                ('show_team_preview', models.BooleanField(default=False)),
                ('show_trust_logos', models.BooleanField(default=False)),
                ('feature_list', models.ManyToManyField(blank=True, to='Accounts.aboutfeature')),
                ('gallery_images', models.ManyToManyField(blank=True, to='Accounts.aboutgalleryimage')),
                ('team_members', models.ManyToManyField(blank=True, to='Accounts.aboutteammember')),
                ('trust_logos', models.ManyToManyField(blank=True, to='Accounts.trustlogo')),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Sections',
            },
        ),
    ]
