# Generated by Django 5.2.2 on 2025-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, to='Accounts.productgalleryimage'),
        ),
    ]
