# Generated by Django 5.2.2 on 2025-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
